name: Build macOS Universal2 App

on:
  push:
    tags:
      - 'v*'   # triggers on any tag starting with v

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-14]  # 13 = Intel, 14 = Arm

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow pyobjc

      - name: Build app with PyInstaller
        run: |
          pyinstaller --windowed \
            --name DuckApp \
            --add-data "duck.webp:Resources" \
            --add-data "duck1.webp:Resources" \
            duck_spawner.py
          mkdir -p dist
          mv dist/DuckApp.app dist/

      - name: Upload artifact (Intel or Arm)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os == 'macos-13' && 'app-intel' || 'app-arm' }}
          path: dist/DuckApp.app

  merge:
    runs-on: macos-14
    needs: build

    steps:
      - name: Download Intel artifact
        uses: actions/download-artifact@v4
        with:
          name: app-intel
          path: dist/intel

      - name: Download Arm artifact
        uses: actions/download-artifact@v4
        with:
          name: app-arm
          path: dist/arm

      - name: Merge into universal2
        run: |
          mkdir -p dist/universal/DuckApp.app/Contents/MacOS
          cp -R dist/intel/DuckApp.app/* dist/universal/DuckApp.app/
          lipo -create \
            dist/intel/DuckApp.app/Contents/MacOS/DuckApp \
            dist/arm/DuckApp.app/Contents/MacOS/DuckApp \
            -output dist/universal/DuckApp.app/Contents/MacOS/DuckApp

      - name: Create DMG
        run: |
          hdiutil create -volname "DuckApp" \
            -srcfolder dist/universal/DuckApp.app \
            -ov -format UDZO dist/DuckApp-universal.dmg

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/DuckApp-universal.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
