name: Build macOS Apple Silicon App

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-14  # Apple Silicon runner

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyqt5 pyobjc

      - name: Build ClickVolume app with PyInstaller
        run: |
          pyinstaller --windowed \
            --name eVolumeC \
            --add-data "1.wav:." \
            --add-data "2.wav:." \
            volume_control.py

          plist_path="dist/eVolumeC.app/Contents/Info.plist"
          /usr/libexec/PlistBuddy -c "Set :LSMinimumSystemVersion 11.0" "$plist_path" || \
            /usr/libexec/PlistBuddy -c "Add :LSMinimumSystemVersion string 11.0" "$plist_path"
          /usr/libexec/PlistBuddy -c "Set :CFBundleSupportedPlatforms:0 MacOSX" "$plist_path" || \
            /usr/libexec/PlistBuddy -c "Add :CFBundleSupportedPlatforms array" "$plist_path"

      - name: Verify architecture
        run: |
          file dist/eVolumeC.app/Contents/MacOS/eVolumeC
          arch dist/eVolumeC.app/Contents/MacOS/eVolumeC

      - name: Create DMG
        run: |
          hdiutil create -volname "eVolumeC" \
            -srcfolder dist/eVolumeC.app \
            -ov -format UDZO \
            dist/eVolumeC-arm64.dmg

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/eVolumeC-arm64.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}