name: Build macOS Universal2 App

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-14]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          set -x
          python -m pip install --upgrade pip
          pip install pyinstaller pillow pyobjc

      - name: Build app with PyInstaller
        run: |
          set -x
          pyinstaller --windowed \
            --name DuckApp \
            --add-data "duck.webp:Resources" \
            --add-data "duck1.webp:Resources" \
            duck_spawner.py

          # fix Info.plist
          plist_path="dist/DuckApp.app/Contents/Info.plist"
          /usr/libexec/PlistBuddy -c "Set :LSMinimumSystemVersion 10.13" "$plist_path" || \
            /usr/libexec/PlistBuddy -c "Add :LSMinimumSystemVersion string 10.13" "$plist_path"
          /usr/libexec/PlistBuddy -c "Set :CFBundleSupportedPlatforms:0 MacOSX" "$plist_path" || \
            /usr/libexec/PlistBuddy -c "Add :CFBundleSupportedPlatforms array" "$plist_path"

          # choose output folder
          if [ "${{ matrix.os }}" = "macos-13" ]; then
            outdir="dist/intel"
          else
            outdir="dist/arm"
          fi

          mkdir -p "$outdir"
          cp -R dist/DuckApp.app "$outdir/"

          echo "Contents of $outdir:"
          ls -lR "$outdir"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os == 'macos-13' && 'app-intel' || 'app-arm' }}
          path: ${{ matrix.os == 'macos-13' && 'dist/intel/DuckApp.app' || 'dist/arm/DuckApp.app' }}

  merge:
    runs-on: macos-14
    needs: build

    steps:
      - name: Download Intel artifact
        uses: actions/download-artifact@v4
        with:
          name: app-intel
          path: dist/intel

      - name: Download Arm artifact
        uses: actions/download-artifact@v4
        with:
          name: app-arm
          path: dist/arm

      - name: Fix artifact structure
        run: |
          set -x
          # If Contents folder exists at root, move it into .app structure
          if [ -d "dist/intel/Contents" ]; then
            echo "Fixing Intel artifact structure"
            mkdir -p dist/intel-fixed/DuckApp.app
            mv dist/intel/* dist/intel-fixed/DuckApp.app/
            rm -rf dist/intel
            mv dist/intel-fixed dist/intel
          fi
          
          if [ -d "dist/arm/Contents" ]; then
            echo "Fixing Arm artifact structure"
            mkdir -p dist/arm-fixed/DuckApp.app
            mv dist/arm/* dist/arm-fixed/DuckApp.app/
            rm -rf dist/arm
            mv dist/arm-fixed dist/arm
          fi
          
          echo "Final structure:"
          ls -l dist/

      - name: Verify .app bundles
        run: |
          set -x
          echo "=== Verifying .app bundles ==="
          ls -la dist/intel/
          ls -la dist/arm/
          
          if [ ! -d "dist/intel/DuckApp.app" ]; then
            echo "ERROR: Intel DuckApp.app not found!"
            exit 1
          fi
          if [ ! -d "dist/arm/DuckApp.app" ]; then
            echo "ERROR: Arm DuckApp.app not found!"
            exit 1
          fi
          
          echo "=== Binary architectures ==="
          file dist/intel/DuckApp.app/Contents/MacOS/DuckApp
          file dist/arm/DuckApp.app/Contents/MacOS/DuckApp

      - name: Merge into universal2
        run: |
          set -x
          mkdir -p dist/universal/DuckApp.app/Contents/MacOS
          
          echo "Copying Intel .app contents..."
          cp -R dist/intel/DuckApp.app/* dist/universal/DuckApp.app/
          
          echo "Running lipo to create universal binary..."
          lipo -create \
            dist/intel/DuckApp.app/Contents/MacOS/DuckApp \
            dist/arm/DuckApp.app/Contents/MacOS/DuckApp \
            -output dist/universal/DuckApp.app/Contents/MacOS/DuckApp
            
          echo "Setting executable permissions..."
          chmod +x dist/universal/DuckApp.app/Contents/MacOS/DuckApp
          
          echo "=== Universal binary info ==="
          lipo -info dist/universal/DuckApp.app/Contents/MacOS/DuckApp
          
      - name: Fix bundle attrs + perms
        run: |
          set -x
          # clear quarantine flags
          xattr -cr dist/universal/DuckApp.app
          # make sure binary is executable
          chmod +x dist/universal/DuckApp.app/Contents/MacOS/DuckApp
          # sanity check
          file dist/universal/DuckApp.app/Contents/MacOS/DuckApp

      - name: Create DMG
        run: |
          set -x
          echo "Creating DMG..."
          hdiutil create -volname "DuckApp" \
            -srcfolder dist/universal \
            -ov -format UDZO \
            dist/DuckApp-universal.dmg
            
          echo "DMG created successfully:"
          ls -lh dist/DuckApp-universal.dmg

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/DuckApp-universal.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}